sudo: required
services: 
  - docker 



before_install:
  - docker build -t vishwa123/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run vishwa123/react-test npm test -- --coverage

after_success:
  - docker build -t vishwa123/multi-client ./client
  - docker build -t vishwa123/multi-nginx ./nginx
  - docker build -t vishwa123/multi-server ./server
  - docker build -t vishwa123/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vishwa123/multi-client
  - docker push vishwa123/multi-nginx
  - docker push vishwa123/multi-server
  - docker push vishwa123/multi-worker


deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi_docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-110731418076
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY


